CREATE TABLE "episodes" (
  "paintingID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" char,
  "season" INT,
  "episode" INT,
  "airDate" DATE
);

CREATE TABLE "colors" (
  "colorID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "colorName" varchar,
  "hexCode" varchar
);

CREATE TABLE "subjects" (
  "subjectID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subjectName" VARCHAR
);

CREATE TABLE "episode_colors" (
  "paintingID" int,
  "colorID" INT
);

CREATE TABLE "episode_subject" (
  "paintingID" INT,
  "subjectID" INT
);

ALTER TABLE "episode_colors" ADD FOREIGN KEY ("paintingID") REFERENCES "episodes" ("paintingID");

ALTER TABLE "episode_colors" ADD FOREIGN KEY ("colorID") REFERENCES "colors" ("colorID");

ALTER TABLE "episode_subject" ADD FOREIGN KEY ("paintingID") REFERENCES "episodes" ("paintingID");

ALTER TABLE "episode_subject" ADD FOREIGN KEY ("subjectID") REFERENCES "subjects" ("subjectID");
